import { BadRequestError } from '@food-delivery/shared';

export const IDEMPOTENCY_KEY_HEADER = 'idempotency-key';
export const IDEMPOTENCY_KEY_MAX_LENGTH = 255;

/** Visible ASCII only (no spaces/control chars), e.g. a UUID v4 generated by the client. */
const IDEMPOTENCY_KEY_PATTERN = /^[\x21-\x7E]+$/;

/**
 * Normalizes the optional `Idempotency-Key` header. Returns undefined when the
 * header is absent; throws BadRequestError when it is present but malformed.
 */
export function parseIdempotencyKey(raw: string | string[] | undefined): string | undefined {
  if (raw === undefined) return undefined;
  if (Array.isArray(raw)) {
    throw new BadRequestError('Idempotency-Key header must be sent once');
  }
  const key = raw.trim();
  if (key.length === 0 || key.length > IDEMPOTENCY_KEY_MAX_LENGTH || !IDEMPOTENCY_KEY_PATTERN.test(key)) {
    throw new BadRequestError(
      `Idempotency-Key must be 1-${IDEMPOTENCY_KEY_MAX_LENGTH} visible ASCII characters (a UUID is recommended)`,
    );
  }
  return key;
}
